**Importing Pandas library for reading the dataset file**

In [ ]:
import pandas as pd

In [ ]:
# Load the datasets
turbine_data = pd.read_csv('A1-turbine.txt', sep='\t', header=None)
synthetic_data = pd.read_csv('A1-synthetic.txt', sep='\t', header=None)

# Display the first few rows of the datasets
print('Turbine Data:')
print(turbine_data.head())
print('\nSynthetic Data:')
print(synthetic_data.head())

Turbine Data:
                        0       1       2      3        4  \
0  #height_over_sea_level    fall     net   fall     flow   
1                  624.00  89.160  89.765  3.500  2512.85   
2                  628.00  93.160  93.765  3.500  2583.79   
3                  602.00  67.840  66.415  6.500  3748.77   
4                  599.00  64.840  63.415  6.500  3520.65   

                                  5  
0  power_of_hydroelectrical_turbine  
1                               NaN  
2                               NaN  
3                               NaN  
4                               NaN  

Synthetic Data:
              0            1            2            3            4  \
0           #v1           v2           v3           v4           v5   
1   37.34411029  10.54215603  0.969185269  3.568534461  96.79873311   
2   4.089848542  11.89430069  0.467774583   1.27904375  100.1493827   
3  -32.33343934  10.96863118  0.238486094  1.410744921  100.6420745   
4  -45.63297745   1

**Pre-Processing**
Now we need to check the dataset,
Is there is any missing value?

In [ ]:
def check_missing_values(data):
    missing_values = data.isnull().sum()
    total_missing_values = missing_values.sum()
    return total_missing_values > 0, total_missing_values

In [ ]:
# Check for missing values in the turbine data
has_missing_values, total_missing_values = check_missing_values(turbine_data)
print(f'Turbine Data: Has missing values? {has_missing_values}, Total missing values: {total_missing_values}')

# Check for missing values in the synthetic data
has_missing_values, total_missing_values = check_missing_values(synthetic_data)
print(f'Synthetic Data: Has missing values? {has_missing_values}, Total missing values: {total_missing_values}')

Turbine Data: Has missing values? True, Total missing values: 451
Synthetic Data: Has missing values? False, Total missing values: 0


In [ ]:
# Remove rows with missing values from the turbine data
turbine_data = turbine_data.dropna()

# Remove rows with missing values from the synthetic data
synthetic_data = synthetic_data.dropna()

# Check again for missing values in the turbine data
has_missing_values, total_missing_values = check_missing_values(turbine_data)
print(f'Turbine Data: Has missing values? {has_missing_values}, Total missing values: {total_missing_values}')

# Check again for missing values in the synthetic data
has_missing_values, total_missing_values = check_missing_values(synthetic_data)
print(f'Synthetic Data: Has missing values? {has_missing_values}, Total missing values: {total_missing_values}')

Turbine Data: Has missing values? False, Total missing values: 0
Synthetic Data: Has missing values? False, Total missing values: 0


In [ ]:
from sklearn.preprocessing import MinMaxScaler

def normalize_data(data):
    scaler = MinMaxScaler()
    normalized_data = scaler.fit_transform(data)
    return normalized_data

In [ ]:
# Load the datasets, skipping non-numeric rows
turbine_data = pd.read_csv('A1-turbine.txt', sep='\t', header=None, comment='#')
synthetic_data = pd.read_csv('A1-synthetic.txt', sep='\t', header=None, comment='#')

# Check for missing values in the turbine data
has_missing_values, total_missing_values = check_missing_values(turbine_data)
print(f'Turbine Data: Has missing values? {has_missing_values}, Total missing values: {total_missing_values}')

# Check for missing values in the synthetic data
has_missing_values, total_missing_values = check_missing_values(synthetic_data)
print(f'Synthetic Data: Has missing values? {has_missing_values}, Total missing values: {total_missing_values}')

# Normalize the turbine data
turbine_data_normalized = normalize_data(turbine_data)

# Normalize the synthetic data
synthetic_data_normalized = normalize_data(synthetic_data)

# Display the first few rows of the normalized datasets
print('Normalized Turbine Data:')
print(turbine_data_normalized[:5])
print('\nNormalized Synthetic Data:')
print(synthetic_data_normalized[:5])

Turbine Data: Has missing values? False, Total missing values: 0
Synthetic Data: Has missing values? False, Total missing values: 0
Normalized Turbine Data:
[[0.84615385 0.82115677 0.84875597 0.08333333 0.14995677]
 [0.94871795 0.92262811 0.94680721 0.08333333 0.1626559 ]
 [0.28205128 0.28031456 0.27638191 0.58333333 0.37120158]
 [0.20512821 0.20421106 0.20284349 0.58333333 0.33036531]
 [1.         0.96144089 0.94129182 0.83333333 0.89482493]]

Normalized Synthetic Data:
[[0.87433469 0.2711503  0.96944516 0.85612733 0.37474332 0.89434557
  0.41492498 0.         0.82977202 0.74661996]
 [0.54123414 0.94753193 0.4678239  0.09229697 0.48250717 0.74746761
  0.43410926 0.         0.21808604 0.35066199]
 [0.17639016 0.48448543 0.23843911 0.13623572 0.49835317 0.6883739
  0.50721657 1.         0.05227501 0.23766133]
 [0.04317164 0.75509664 0.92517962 0.80125748 0.66948571 0.55949881
  0.64084071 0.         0.82509078 0.81476651]
 [0.08413609 0.05856788 0.31516497 0.0059135  0.39316222 0.517425

In [ ]:
class NeuralNet:
    def __init__(self, layers):
        self.L = len(layers)
        self.n = layers.copy()

        self.xi = []
        for lay in range(self.L):
            self.xi.append(np.zeros(layers[lay]))

        self.w = []
        self.w.append(np.zeros((1, 1)))
        for lay in range(1, self.L):
            self.w.append(np.zeros((layers[lay], layers[lay - 1])))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def forward_pass(self, x):
        self.xi[0] = x
        for lay in range(1, self.L):
            self.xi[lay] = self.sigmoid(np.dot(self.w[lay], self.xi[lay - 1]))
        return self.xi[-1]

    def backward_pass(self, y):
        self.delta = [0] * self.L
        self.delta[-1] = (self.xi[-1] - y) * self.xi[-1] * (1 - self.xi[-1])
        for lay in range(self.L - 2, -1, -1):
            self.delta[lay] = np.dot(self.w[lay + 1].T, self.delta[lay + 1]) * self.xi[lay] * (1 - self.xi[lay])
        return self.delta

    def update_weights(self, lr):
        for lay in range(self.L - 1, 0, -1):
            self.w[lay] -= lr * np.dot(self.delta[lay].reshape(-1, 1), self.xi[lay - 1].reshape(1, -1))
        return self.w

    def train(self, X, y, epochs, lr):
        history = []
        for epoch in range(epochs):
            for i in range(X.shape[0]):
                output = self.forward_pass(X[i].reshape(-1, 1))
                self.backward_pass(y[i])
                self.update_weights(lr)
            if epoch % 100 == 0:
                loss = np.mean(np.square(y - self.forward_pass(X.T)))
                history.append(loss)
                print(f'Epoch {epoch}: loss {loss}')
        return history

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

def load_data(file_path):
    data = pd.read_csv(file_path, sep='\t', header=None)
    X = data.iloc[:, :-1].values
    y = data.iloc[:, -1].values
    return X, y

def preprocess_data(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    scaler = MinMaxScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    return X_train, X_test, y_train, y_test


In [ ]:
def load_data(file_path):
    data = pd.read_csv(file_path, sep='\t', header=None, skiprows=1)
    X = data.iloc[:, :-1].values
    y = data.iloc[:, -1].values
    return X, y

X_turbine, y_turbine = load_data('A1-turbine.txt')
X_synthetic, y_synthetic = load_data('A1-synthetic.txt')

X_train_turbine, X_test_turbine, y_train_turbine, y_test_turbine = preprocess_data(X_turbine, y_turbine)
X_train_synthetic, X_test_synthetic, y_train_synthetic, y_test_synthetic = preprocess_data(X_synthetic, y_synthetic)

In [ ]:
import numpy as np
nn_turbine = NeuralNet([4, 5, 1])
nn_synthetic = NeuralNet([9, 5, 1])

history_turbine = nn_turbine.train(X_train_turbine, y_train_turbine, epochs=1000, lr=0.1)
history_synthetic = nn_synthetic.train(X_train_synthetic, y_train_synthetic, epochs=1000, lr=0.1)

Epoch 0: loss 16285916.015195556
Epoch 100: loss 16285916.015195556
Epoch 200: loss 16285916.015195556
Epoch 300: loss 16285916.015195556
Epoch 400: loss 16285916.015195556
Epoch 500: loss 16285916.015195556
Epoch 600: loss 16285916.015195556
Epoch 700: loss 16285916.015195556
Epoch 800: loss 16285916.015195556
Epoch 900: loss 16285916.015195556
Epoch 0: loss 42.222145971922245
Epoch 100: loss 42.21538865592272
Epoch 200: loss 42.215360353716676
Epoch 300: loss 42.21535096987551
Epoch 400: loss 42.21534629739921
Epoch 500: loss 42.21534350295044
Epoch 600: loss 42.2153416448421
Epoch 700: loss 42.21534032051051
Epoch 800: loss 42.215339329110094
Epoch 900: loss 42.21533855927064
